config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "pages#home"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :cars, only: [:index, :show, :new, :create, :destroy] do
    collection do
      get :mycars
    end
    resources :reservations, only: [:new, :create]
  end
  resources :reservations, only: [:index, :show, :update, :destroy] do
    collection do
      get :mycars
    end
    resources :reviews, only: [:create]
  end
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.

  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/car.rb
class Car < ApplicationRecord
  belongs_to :user
  has_many :reservations, dependent: :destroy
  validates :brand, presence: true
  validates :car_model, presence: true
  validates :car_location, presence: true
  validates :rent_price, presence: true, numericality: true
  validates :kilometers, numericality: true, allow_nil: true
  validates :release_year, numericality: { only_integer: true }, allow_nil: true
  has_one_attached :photo
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :car
  belongs_to :user
  has_many :reviews, dependent: :destroy

  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :end_date, comparison: { greater_than_or_equal_to: :start_date }
  validates :total_price, presence: true, numericality: true
  validates :status, presence: true, inclusion: { in: ["Pending", "Accepted", "Rejected"], allow_nil: false }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :reservation

  AUTHORIZED_RATINGS = (1..5)

  validates :content, presence: true
  validates :rating, presence: true, inclusion: { in: AUTHORIZED_RATINGS }
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cars, dependent: :destroy
  has_many :reservations, dependent: :destroy

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :email, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, unless: :devise_controller?
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    cars_path  # Redirige vers la liste des voitures après connexion
  end

  def after_sign_out_path_for(resource_or_scope)
    root_path  # Redirige vers la page d'accueil après déconnexion
  end

  private

  # dans le cours on donne ça mais ça ne marche pas va savoir pourquoi
  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end

  def devise_controller?
    is_a?(Devise::SessionsController) || is_a?(Devise::RegistrationsController) || is_a?(Devise::PasswordsController)
  end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  def index
    @cars = Car.all
  end

  def show
    @car = Car.find(params[:id])
    @reservation = Reservation.new
  end

  def new
    @car = Car.new
  end

  def create
    @car = Car.new(car_params)
    @car.user_id = current_user.id
    if @car.save
      redirect_to @car, notice: "Voiture ajoutée avec succès !"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @car = Car.find(params[:id])
    if @car.destroy
      redirect_to cars_path
    else
      render :show, status: :unprocessable_entity
    end
  end

  def mycars
    @cars = Car.where(user_id: current_user.id)
  end

  private

  def car_params
    params.require(:car).permit(:brand, :car_model, :car_location, :rent_price, :kilometers, :release_year, :photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
    @car = Car.where("brand LIKE ?", "Tesla").first
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  def index
    @reservations = Reservation.all.select { |reservation| reservation.user_id == current_user.id }
  end

  def create
    @reservation = Reservation.new(reservation_params)
    @reservation.car_id = params[:car_id]
    @reservation.user_id = current_user.id
    @reservation.total_price = (@reservation.end_date - @reservation.start_date + 1) * @reservation.car.rent_price
    @reservation.status = "Pending"
    if @reservation.save!
      redirect_to reservations_path
    else
      redirect_to car_path(Car.find(@reservation.car_id))
    end
  end

  def show
    @reservation = Reservation.find(params[:id])
    @review = Review.new
  end

  def destroy
    @reservation = Reservation.find(params[:id])
    @reservation.destroy
    redirect_to reservations_path
  end

  def update
    status = {"Accepter": "Accepted", "Refuser": "Rejected"}
    @reservation = Reservation.find(params[:id])
    if @reservation.update(status: status[params["status"].to_sym])
      redirect_to reservation_path(@reservation)
    else
      redirect_to reservation_path(@reservation)
    end
  end

  def mycars
    @reservations = Reservation.where(car_id: Car.where(user_id: current_user.id).map { |car| car.id })
  end

  private

  def reservation_params
    params.require(:reservation).permit(:start_date, :end_date, :total_price, :status, :car_id, :user_id)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_reservation, only: [:create]

  def create
    @review = Review.new(review_params)
    @review.reservation = @reservation
    if @review.save
      redirect_to reservation_path(@reservation)
    else
      redirect_to reservation_path(@reservation)
      # render "reservations/show", status: :unprocessable_entity
    end
  end

  private

  def set_reservation
    @reservation = Reservation.find(params[:reservation_id])
  end

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_footer.html.erb
<div class="footer-basic">
  <footer>
    <div class="social">
      <a href="#"><i class="fa-brands fa-instagram"></i></a>
      <a href="#"><i class="fa-brands fa-twitter"></i></a>
      <a href="#"><i class="fa-brands fa-meta"></i></a>
    </div>
    <ul class="list-inline">
      <li class="list-inline-item"><a href="#">Home</a></li>
      <li class="list-inline-item"><a href="#">Contact</a></li>
      <li class="list-inline-item"><a href="#">Infos</a></li>
      <li class="list-inline-item"><a href="#">Conditions générales</a></li>
      <li class="list-inline-item"><a href="#">Confidentialité</a></li>
    </ul>
    <p class="copyright">Car B&B © 2025</p>
  </footer>
</div>

app/views/cars/_car_card.html.erb
<div class="car-card">
  <%= image_tag car.photo.attached? ? url_for(car.photo) : 'default_car.jpg', alt: car.brand, class: "car-image" %>
  <div class="car-card-info">
    <h3><%= car.brand %> - <%= car.car_model %></h3>
    <p><strong><i class="fa-solid fa-location-dot"></i> </strong> <%= car.car_location %></p>
    <p><strong><i class="fa-solid fa-euro-sign"></i> </strong> <%= number_to_currency(car.rent_price, unit: "") %> par jour</p>
  </div>
</div>

app/views/cars/_car_card_link.html.erb
<%= link_to car_path(car) do %>
  <%= render "cars/car_card", car: car %>
<% end %>

app/views/cars/index.html.erb
<!-- app/views/cars/index.html.erb -->
<div class="our-container">
  <h1>Découvrez des voitures d'exception</h1>

  <div class="cars-container">
    <% @cars.each do |car| %>
      <%= render "car_card_link", car: car %>
    <% end %>
  </div>
</div>

app/views/cars/mycars.html.erb
<div class="our-container">
  <% if @cars.empty? %>
    <h1>Il semblerait que vous n'ayez pas renseigné de voitures...</h1>
    <%= link_to "Ajouter une voiture !", new_car_path, class: "our-btn our-btn-success d-block mt-5" %>
  <% else %>
    <h1>Vos voitures</h1>

    <div class="cars-container">
      <% @cars.each do |car| %>
        <%= render "car_card_link", car: car %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/cars/new.html.erb
<div class="container-form mt-5 mb-5" id="new-car-container">
  <h1>Ajouter une voiture</h1>

  <%= form_with model: @car, local: true do |f| %>

    <div class="row g-3">
      <div class="form-group col">
        <%= f.label :brand, "Marque" %>
        <%= f.text_field :brand, class: "form-control" %>
      </div>

      <div class="form-group col">
        <%= f.label :car_model, "Modèle" %>
        <%= f.text_field :car_model, class: "form-control" %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :car_location, "Localisation" %>
      <%= f.text_field :car_location, class: "form-control" %>
    </div>

    <div class="row g-3">
      <div class="form-group col">
        <%= f.label :rent_price, "Prix de location (€)" %>
        <%= f.number_field :rent_price, class: "form-control" %>
      </div>

      <div class="form-group col">
        <%= f.label :kilometers, "Kilométrage (km)" %>
        <%= f.number_field :kilometers, class: "form-control" %>
      </div>

      <div class="form-group col">
        <%= f.label :release_year, "Année de sortie" %>
        <%= f.number_field :release_year, class: "form-control" %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :photo, "Photo" %>
      <%= f.file_field :photo, class: "form-control" %>
    </div>

    <%= f.submit "Ajouter la voiture", class: "our-btn our-btn-success mt-3" %>
  <% end %>

  <%= link_to "Retour à la liste", cars_path, class: "our-btn our-btn-default mt-3", id: "retour-cars-new" %>
</div>

app/views/cars/show.html.erb
<div class="car-reservation-container">
    <div class="car-show-container">
      <% if @car.photo.attached? %>
        <%= image_tag @car.photo, class: "car-image" %>
      <% else %>
        <%= image_tag 'default_car.jpg', class: "car-image" %>
      <% end %>

      <div class="car-details">
        <h1 class="car-title gold-text"><%= @car.brand %> - <%= @car.car_model %></h1>
        <p class="car-location"><i class="fa-solid fa-location-dot"></i>  <span class="gold-text ms-3"><%= @car.car_location %></span></p>
        <p class="car-price"> <i class="fa-solid fa-euro-sign"></i> <span class="gold-text ms-3"><%= number_to_currency(@car.rent_price, unit: "") %></span> / jour</p>
        <p class="car-kilometers"><i class="fa-solid fa-road"></i> <span class="gold-text ms-2"><%= @car.kilometers %></span> km</p>
        <p class="car-year"> Fabriquée en <span class="gold-text"><%= @car.release_year %></span></p>
      </div>

      <%= link_to cars_path, class: "back-arrow" do %>
      <i class="fa-solid fa-arrow-left"></i> Retour
      <% end %>
    </div>

    <div class="right-side-car-show">
      <% if current_user.id == @car.user_id %>
        <%= link_to "Retirer la voiture", car_path(@car), data: { turbo_method: :delete, turbo_confirm: "Retirer votre voiture ?" }, class: "our-btn our-btn-danger", id: "delete-car" %>
      <% end %>
      <% if @car.user_id != current_user.id %>
        <div class="reservation-form">
          <%= render "reservations/reservation_form", reservation: @reservation, car: @car %>
        </div>
      <% end %>
      <% reservations = @car.reservations.select { |res| res.status == "Accepted" } %>
      <%= render "reviews/review", reservations: reservations, car: @car %>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AirbnbCars</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "navbar" %>
    <%= yield %>
    <%= render "footer" %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="home-page-container">
  <div class="home-page-welcome" style="background-image: url(<%= cl_image_path(@car.photo.key) %>)">
    <div class="home-page-text">
      <h1>CAR B&B</h1>
      <h3>Louez l'Excellence, Roulez le Rêve</h3>
      <p>Découvrez une sélection exclusive de voitures de prestige, alliant élégance, puissance et raffinement. Que ce soit pour un événement spécial, un voyage d'affaires ou simplement pour le plaisir de conduire l'exception, Car B&B vous offre une expérience unique. Réservez en toute simplicité et prenez le volant de l'extraordinaire. </p>
    </div>
  </div>
</div>

app/views/reservations/_confirm_reservation.html.erb
<% if reservation.status == "Pending" && other == "Locataire"%>
  <%= simple_form_for(reservation, html: {style: "background-color: transparent; box-shadow: none; padding: 20px 0px;"}) do |f| %>
    <div class="d-flex justify-space-between gap-4" style="width: 100px;">
      <%= f.submit  name: "status", value: "Accepter", class: "our-btn our-btn-success ms-0 border-0" %>
      <%= f.submit  name: "status", value: "Refuser", class: "our-btn our-btn-danger border-0" %>
    </div>
  <% end %>
<% end %>

app/views/reservations/_reservation_card.html.erb
<% car = reservation.car %>
<div class="reservation-container"
    style="background-image: linear-gradient(to bottom, rgba(255,255,255,0.1) 0%, rgba(0,0,0,0.5) 50%, rgba(0,0,0,0.9) 100%),
                              url(<%= cl_image_path(car.photo.key)%>);">
  <div class="reservation-card-info">
    <div class="reservation-title">
      <h4><%= car.brand %> - <%= car.car_model %></h4>
    </div>
    <div class="reservation-location">
      <p><strong><i class="fa-solid fa-location-dot"></i> </strong> <%= car.car_location %></p>
    </div>
    <div class="reservation-info">
      <div class="reservation-dates-text">
        <p><span class="reservation-date-text">Date de début</span></p>
        <p><span class="reservation-date-text">Date de fin</span></p>
      </div>
      <div class="reservation-dates">
        <p> <%= reservation.start_date.strftime('%d %b, %Y')%></p>
        <p> <%= reservation.end_date.strftime('%d %b, %Y') %></p>
      </div>
      <div class="reservation-price">
        <p><strong><i class="fa-solid fa-euro-sign"></i> </strong> <%= number_to_currency(reservation.total_price, unit: "") %></p>
      </div>
    </div>
  </div>

</div>

app/views/reservations/_reservation_card_link.html.erb
<%= link_to reservation_path(reservation) do %>
  <%= render "reservation_card", reservation: reservation %>
<% end %>

app/views/reservations/_reservation_form.html.erb
<h3 class="gold-text">Réservation</h3>
<%= simple_form_for [car, reservation] do |f| %>
  <div class="row">
    <%= f.input :start_date, html5: true, label: "Date de début" %>
  </div>
  <div class="row">
    <%= f.input :end_date, html5: true, label: "Date de fin" %>
  </div>
  <%= f.submit "Reservez", class: "our-btn our-btn-success" %>
<% end %>

app/views/reservations/_user_information_reservation.html.erb
<h2 class="reservation-show-title">Informations de réservation</h2>

<% if reservation.status == "Pending" && other == "Propriétaire" %>
  <%= link_to reservation_path(@reservation), id: "annuler-reservation", data: { turbo_method: :delete, turbo_confirm: "Annuler la réservation ?" } do %>
    <i class="fa-solid fa-circle-xmark"></i>
  <% end %>
<% end %>
</div>

<div class="reservation-show-owner">
  <h5 class="mt-5 mb-5"><%= other %> - <span class="gold-text"><%= user.first_name.capitalize %> <%= user.last_name.capitalize %></span></h5>

  <div class="reservation-show-owner-coordinates">

    <div class="reservation-show-owner-text">
      <h6><i class="fa-solid fa-envelope"></i></h6>
      <% if user.phone_number %>
        <h6><i class="fa-solid fa-phone"></i></h6>
      <% end %>
    </div>
    <div class="reservation-show-owner-values">
      <h6 class="gold-text">  <%= user.email %></h6>
      <% if user.phone_number %>
        <h6 class="gold-text">  <%= user.phone_number %></h6>
      <% end %>
    </div>
  </div>
</div>

app/views/reservations/index.html.erb
<div class="our-container">

  <% if @reservations.empty? %>
    <h1 class="gold-text">Il semblerait que vous n'avez pas de réservations...</h1>
    <%= link_to "Découvrez nos modèles !", cars_path, class: "our-btn our-btn-success d-block mt-5" %>
  <% else %>
    <h1 class="gold-text">Mes réservations</h1>

    <div class="reservations-container">
      <% @reservations.each do |reservation| %>
        <%= render "reservation_card_link", reservation: reservation %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/reservations/mycars.html.erb
<div class="our-container">

  <% if @reservations.empty? %>
    <h1 class="gold-text">Il semblerait qu'il n'y ait pas encore de locations sur vos voitures...</h1>
  <% else %>
    <h1>Liste des réservations sur mes voitures</h1>

    <div class="reservations-container">
      <% @reservations.each do |reservation| %>
        <%= render "reservation_card_link", reservation: reservation %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/reservations/show.html.erb
<% car = @reservation.car %>
<% color = "danger" if @reservation.status == "Rejected" %>
<% color = "success" if @reservation.status == "Accepted" %>
<% color = "warning" if @reservation.status == "Pending" %>

<% status = {"Rejected": "Rejetée", "Accepted": "Acceptée", "Pending": "En attente"} %>

<div class="reservation-show-container">

  <div class="reservation-show-info">

    <div class="reservation-show-info-header">
      <% if current_user.id != car.user_id %>
        <% user = car.user %>
        <% other = "Propriétaire" %>
      <% elsif current_user.id == car.user_id %>
        <% user = User.find(@reservation.user_id) %>
        <% other = "Locataire" %>
      <% end %>

      <%= render "user_information_reservation",
          user: user,
          reservation: @reservation,
          other: other %>

    <div class="reservation-show-dates">
      <div class="reservation-show-date-text">
        <h5>Date de début</h5>
        <h5>Date de fin</h5>
      </div>
      <div class="reservation-show-date-value">
        <h5 class="gold-text"><%= @reservation.start_date.strftime('%d %b, %Y')%></h5>
        <h5 class="gold-text"><%= @reservation.end_date.strftime('%d %b, %Y') %></h5>
      </div>
    </div>

    <div>
      <h5 class="bg-<%= color %> reservation-show-status"><%= status[@reservation.status.to_sym] %></h5>
    </div>

    <%= render "confirm_reservation", reservation: @reservation, other: other %>

  </div>

  <div class="reservation-show-car">
    <%= render "cars/car_card_link", car: car %>
  </div>

</div>

<% if @reservation.status == "Accepted" && @reservation.end_date <= Date.today %>
<div class="our-container mb-5">
  <div class="row">
    <div class="col-6" id="review-form">
      <% if car.user_id != current_user.id %>
        <%= render "reviews/form", reservation: @reservation, review: @review %>
      <% end %>
    </div>

    <div class="col-6 review-list">
      <h1 class="gold-text mx-0">Avis</h1>
      <ul class="list-group">
        <% @reservation.reviews.each do |review| %>
          <li class="list-group-item">
            <div class="review-title">
              <p class="review-user gold-text fw-700">
                <%= @reservation.user.first_name.capitalize %> <%= @reservation.user.last_name.capitalize %>
              </p>
              <p class="review-stars">
                <% Review::AUTHORIZED_RATINGS.each do |number| %>
                  <i class="fa<%= (number > review.rating) ? 'r' : 's' %> fa-star"></i>
                <% end %>
              </p>
            </div>
            <div class="review-content">
              <%= review.content %>
            </div>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>
<% else %>
<% end %>

app/views/reviews/_form.html.erb
<h1 class="gold-text mx-0">Laissez un avis</h1>
<%= simple_form_for [reservation, review] do |f| %>
  <%= f.input :content, label: 'Commentaires' %>
  <%= f.input :rating, label: 'Évaluation globale', collection: Review::AUTHORIZED_RATINGS, include_blank: false %>
  <%= f.submit "Publiez votre avis", class: "our-btn our-btn-success" %>
<% end %>

app/views/reviews/_review.html.erb
<%# <% if @reservation.status == "Accepted" && @reservation.end_date <= Date.today %>

<%# <div class="our-container"> %>
    <div class="review-list" style="width: 80%;">
      <% if reservations.find { |res| !res.reviews.empty? } %>
        <h1 class="gold-text mx-0">Avis</h1>
        <ul class="list-group">
          <% reservations.each do |reservation| %>
            <% reservation.reviews.each do |review| %>
              <li class="list-group-item">
                <div class="review-title">
                  <p class="review-user gold-text fw-700">
                    <%= reservation.user.first_name.capitalize %> <%= reservation.user.last_name.capitalize %>
                  </p>
                  <p class="review-stars">
                    <% Review::AUTHORIZED_RATINGS.each do |number| %>
                      <i class="fa<%= (number > review.rating) ? 'r' : 's' %> fa-star"></i>
                    <% end %>
                  </p>
                </div>
                <div class="review-content">
                  <%= review.content %>
                </div>
              </li>
            <% end %>
          <% end %>
        </ul>
    <% end %>
  </div>
<%# </div> %>